import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FDEFF4',
    padding: 20,
  },
  title: {
    fontSize: 26,
    color: '#D36B9B',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
  },
  title2: {
    fontSize: 22,
    color: '#D36B9B',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 15,
  },
  input: {
    borderWidth: 1,
    borderColor: '#D36B9B',
    borderRadius: 10,
    padding: 12,
    marginBottom: 15,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#6A6A6A',
  },
  message: {
    color: '#FF3366',
    textAlign: 'center',
    marginTop: 10,
    fontSize: 16,
  },
  propertyList: {
    marginTop: 20,
  },
  card: {
    backgroundColor: '#F9DDE7',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  cardText: {
    color: '#333333',
    fontSize: 16,
    marginBottom: 5,
  },
  cardButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  button: {
    borderRadius: 8,
    marginTop: 5,
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: '#D36B9B',
    alignItems: 'center',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  buttonSecondary: {
    backgroundColor: '#FF8C94',
  },
  navbar: {
    paddingTop: 40,
    backgroundColor: '#FDEFF4',
    paddingBottom: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  logo: {
    fontSize: 28,
    fontFamily: 'Italianno',
    color: '#D36B9B',
    fontWeight: 'bold',
    marginBottom: 10,
  },
  weatherContainer: {
    backgroundColor: '#F9DDE7',
    padding: 20,
    borderRadius: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weatherTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#D36B9B',
    marginBottom: 15,
    textAlign: 'center',
  },
  weatherInfo: {
    fontSize: 16,
    color: '#6A6A6A',
    textAlign: 'center',
    marginBottom: 8,
  },
  weatherTemperature: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#D36B9B',
    marginTop: 10,
    textAlign: 'center',
  },
  weatherIcon: {
    width: 85,
    height: 60,
    marginTop: 15,
  },
  resultContainer: {
    backgroundColor: '#F9DDE7',
    padding: 15,
    borderRadius: 12,
    marginTop: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  resultText: {
    fontSize: 16,
    color: '#333333',
    marginBottom: 5,
  },
});
